// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBztBMFs3fis_x4A0iHPoe-MvLM1rfwZ3E',
    appId: '1:561914010451:web:cd36a9e1eb2b6358091fa6',
    messagingSenderId: '561914010451',
    projectId: 'afrinet-d6fb8',
    authDomain: 'afrinet-d6fb8.firebaseapp.com',
    storageBucket: 'afrinet-d6fb8.firebasestorage.app',
    measurementId: 'G-VF7EPX79FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkRSRzQFsV2VoOP9ZNXSRDaUhWtskroU',
    appId: '1:561914010451:android:7412b2125dbe4ce1091fa6',
    messagingSenderId: '561914010451',
    projectId: 'afrinet-d6fb8',
    storageBucket: 'afrinet-d6fb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1vl_oufx4O9XeRsnw8VD_JnqX5kSOL-E',
    appId: '1:561914010451:ios:010a724fd4cfb676091fa6',
    messagingSenderId: '561914010451',
    projectId: 'afrinet-d6fb8',
    storageBucket: 'afrinet-d6fb8.firebasestorage.app',
    iosBundleId: 'com.example.afriNumber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1vl_oufx4O9XeRsnw8VD_JnqX5kSOL-E',
    appId: '1:561914010451:ios:010a724fd4cfb676091fa6',
    messagingSenderId: '561914010451',
    projectId: 'afrinet-d6fb8',
    storageBucket: 'afrinet-d6fb8.firebasestorage.app',
    iosBundleId: 'com.example.afriNumber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBztBMFs3fis_x4A0iHPoe-MvLM1rfwZ3E',
    appId: '1:561914010451:web:727e969eee0168dd091fa6',
    messagingSenderId: '561914010451',
    projectId: 'afrinet-d6fb8',
    authDomain: 'afrinet-d6fb8.firebaseapp.com',
    storageBucket: 'afrinet-d6fb8.firebasestorage.app',
    measurementId: 'G-YV748R4GHC',
  );
}
